### PR TITLE
Adding aws-sdk

### PR DESCRIPTION
**Pull request by michaelwills**

### CODE REVIEW

**Comment by kellyjandrews** [comment]
@michaelwills - looks like there is a merge conflict here - can you take a look and resubmit the pull request?

**Comment by michaelwills** [comment]
@kellyjandrews resolved after some Github UI thrashing. Sorry I didn't see the notification

**Comment by kellyjandrews** [comment]
No worries. I'll take a look and get this closed out shortly.

**Comment by michaelwills** [comment]
Thanks much @kellyjandrews

**Comment by kotchaosu** [comment]
@michaelwills neat! let's merge it!

**Pull request merged**
