### PR TITLE
Revert "add mailgun-js"

### PR DESCRIPTION
**Pull request by kellyjandrews**
Reverts Syncano/nodejs-codebox#32

### CODE REVIEW

**Comment by kotchaosu** [comment]
why?

**Comment by MariuszWisniewski** [comment]
@Zhebr sorry, I asked Kelly to revert, I thought we had no tests for CB on Circle :)

**Comment by kotchaosu** [comment]
@lifcio you're wrong - we have :)

**Comment by kotchaosu** [comment]
@kellyjandrews I stopped build on circle and I'm closing the PR

**Pull request closed without merging**
