### PR TITLE
adding sparkpost

### PR DESCRIPTION
**Pull request by kellyjandrews**

### CODE REVIEW

**Comment by devintyler** [comment]
version checks out - I know we need this for integrations

**Comment by 23doors** [comment]
@kellyjandrews do not merge until tests are passing or ideally until a dev takes a look. Merging pushes it to registry which can cause a lot of issues. Also, delete branch after merging.

**Comment by 23doors** [comment]
Why would you cancel the build? Those changes won't go live immediately anyway, why rush it?

**Comment by kellyjandrews** [comment]
Was going to delete the branch after the build passed.  I cancelled the duplicate build.

**Comment by 23doors** [comment]
It's not duplicate though. Master build can sometimes have separate logic. These tests are simple but still they are here for a reason :P

**Comment by kellyjandrews** [comment]
Sorry - thought I might have hit the "rerun" button, and was canceling the additional test being run on the patch branch.

**Comment by kotchaosu** [comment]
@kellyjandrews take into account node codebox takes a lot of time to build so deploying fixes is quite painful currently; it's minor change, so it's not a big deal, but keep in mind every change needs review - please let me know if you need things ASAP

**Pull request merged**
