### PR TITLE
Adding Keen.io package

### PR DESCRIPTION
**Pull request by kellyjandrews**

### CODE REVIEW

**Comment by kellyjandrews** [comment]
Had to create new branch - I don't have the ability to push to the repo from remote for some reason.

**Comment by 23doors** [comment]
Creating/deleting is pushing just as well ;) you could have merged it locally, fix conflicts and push that merge commit to existing branch

**Comment by kellyjandrews** [comment]
That's what I am saying - it wouldn't allow me to push the changes remotely. For some reason, my authentication was failing - although it works in the browser.  It also wouldn't allow SSH, only HTTP.  So - I went down that path, and it didn't work - so I had to delete the old branch and create a new one.

**Comment by kellyjandrews** [comment]
@23doors Does it look ok to merge?

**Comment by 23doors** [comment]
looks good!

**Comment by kellyjandrews** [comment]
Thanks!

**Pull request merged**
